#!/bin/bash -x

# updated 16:04

# Unpack the dicom/nifti image

export FLYWHEEL=${FLYWHEEL:=/flywheel/v0}
export PATH=${FLYWHEEL}:$PATH

export FLYWHEEL_INPUTDIR="${FLYWHEEL}/input"
export FLYWHEEL_OUTPUTDIR="${FLYWHEEL}/output"

CONFIG_FILE=${FLYWHEEL}/config.json

echo 35.184.111.29 dss.itksnap.org >> /etc/hosts

echo "/flywheel/v0"
ls -lR /flywheel/v0

cat "$CONFIG_FILE"

installFWSupportFiles

if [ -e "/root/.alfabis/server" -a -e "/root/.alfabis/cookie_"*".jar" ]
then
	echo "Found itksnap cookie jar"
else
	echo "No itksnap cookie found.  Bailing"
	exit 1
fi

itksnap-wt -dss-tickets-list

echo Zipfiles in $FLYWHEEL_INPUTDIR:
find ${FLYWHEEL_INPUTDIR} -type f | grep '.zip$'

# Run the pipeline

while read line
do
    ExtractDir=$(mktemp -d /tmp/ashsharpicv-XXXXXX)
    
    if echo "$line" | grep -q '.nii.gz$'
    then
	ExtractDir="$line"
    else
	dirname=$(dirname "$line")
	basename=$(basename "$line")
	(echo cd "$dirname"; cd "$dirname"; echo unzip -j $basename -d "${ExtractDir}"; unzip -j "$basename" -d "$ExtractDir")
    fi

    ProjectName=$(getGearParam ProjectName ImageComments UnknownProjectName)
    if [ "$ProjectName" == "UnknownProjectName" ]
    then
	ProjectID=$(jq -r '.["destination"]["id"]' "$CONFIG_FILE")
	ProjectName=$(getFWParent "$ProjectID")
    fi

    Age=$(getGearParam Age PatientAge UnknownAge)
    SessionID=$(getGearParam SessionID StudyDescription UnknownSessionID)
    SubjectID=$(getGearParam SubjectID SeriesDescription UnknownSubjectID)
    
    if ! ( echo "$Age" | grep -q '^[0-9][0-9]*$' )
    then
	# R markdown will fail if Age is not a number
	echo "Age '$Age' for '$ProjectName/$SessionID/$ScanID' is not a number.  Skipping." 1>&2
	continue
    fi

    # R markdown boofs if the SessionID has a ^ in it.
    SessionID=$(echo "$SessionID" | sed 's/\^/-/g')

    run_pipeline.sh -s "$SessionID" -n "$ScanID" -p "$ProjectName" -a "$Age" "$ExtractDir" "$FLYWHEEL_OUTPUTDIR"
done < <(find ${FLYWHEEL_INPUTDIR} -type f | grep -P '(\.zip|.gz)$')


echo "/flywheel/v0"
ls -lR /flywheel/v0

