#!/bin/bash -x

# updated 16:04

# Unpack the dicom/nifti image

export FLYWHEEL=${FLYWHEEL:=/flywheel/v0}
export PATH=${FLYWHEEL}:/usr/local/flywheel/bin:$PATH
export PYTHONPATH=/usr/local/pyjq:/usr/local/flywheel/lib

export FLYWHEEL_INPUTDIR="${FLYWHEEL}/input"
export FLYWHEEL_OUTPUTDIR="${FLYWHEEL}/output"

CONFIG_FILE=${FLYWHEEL}/config.json

echo 35.184.111.29 dss.itksnap.org >> /etc/hosts

echo "/flywheel/v0"
ls -lR /flywheel/v0

cat "$CONFIG_FILE"

installFWSupportFiles

if [ -e "/root/.alfabis/server" -a -e "/root/.alfabis/cookie_"*".jar" ]
then
	echo "Found itksnap cookie jar"
else
	echo "No itksnap cookie found.  Bailing"
	exit 1
fi

itksnap-wt -dss-tickets-list

echo Zipfiles in $FLYWHEEL_INPUTDIR:
find ${FLYWHEEL_INPUTDIR} -type f | grep '.zip$'

# Run the pipeline

while read line
do
    ExtractDir=$(mktemp -d /tmp/ashsharpicv-XXXXXX)
    
    if echo "$line" | grep -q '.nii.gz$'
    then
	ExtractDir="$line"
    else
	dirname=$(dirname "$line")
	basename=$(basename "$line")
	(echo cd "$dirname"; cd "$dirname"; echo unzip -j $basename -d "${ExtractDir}"; unzip -j "$basename" -d "$ExtractDir")
    fi

    # Really want the input fwID to track back the session/subject ID
    # If you don't have the gear/dicom ids, you don't have the subject/session chain
    #
    # Want to get the input dicom id from the config file, look it up in flywheel and pass the output to jq

    ProjectName=$(getGearParam "${CONFIG_FILE}:.config.ProjectName" "fwget:${CONFIG_FILE},.destination.id,.parents.project,.label" "${CONFIG_FILE}:.inputs.dicom.object.info.ImageComments" default:UnknownProjectName)

    SubjectID=$(getGearParam "${CONFIG_FILE}:.config.SubjectID" "fwget:${CONFIG_FILE},.destination.id,.parents.subject,.label" "${CONFIG_FILE}:.inputs.dicom.object.info.SeriesDescription" UnknownSubjectID)

    SessionID=$(getGearParam "${CONFIG_FILE}:.config.SessionID" "fwget:${CONFIG_FILE},.destination.id,.parents.session,.label" "${CONFIG_FILE}:.inputs.dicom.object.info.StudyDescription" UnknownSession)

    Age=$(getGearParam "${CONFIG_FILE}:.config.Age" "${CONFIG_FILE}:.inputs.dicom.object.info.PatientAge" UnknownAge)

    # See if the age is in months and then take the floor of the age in months/12 (Arun's recommendataion)
    if echo "$Age" | grep -qP '\d+M$'
    then
	AgeInMonths=$(echo "$Age" | sed 's/M$//')
	Age=$(("$AgeInMonths" / 12))
    fi

    # deal with 081Y
    if echo "$Age" | grep -qP '0\d+Y$'
    then
	Age=$(echo "$Age" | sed 's/^0//; s/Y$//')
    fi
	
    if ! ( echo "$Age" | grep -q '^[0-9][0-9]*$' )
    then
	# R markdown will fail if Age is not a number
	echo "Age '$Age' for '$ProjectName/$SessionID/$ScanID' is not an integer.  Skipping." 1>&2
	continue
    fi

    # R markdown boofs if the SessionID has a ^ in it.
    SessionID=$(echo "$SessionID" | sed 's/\^/-/g')

    run_pipeline.sh -s "$SessionID" -n "$SubjectID" -p "$ProjectName" -a "$Age" "$ExtractDir" "$FLYWHEEL_OUTPUTDIR"
done < <(find ${FLYWHEEL_INPUTDIR} -type f | grep -P '(\.zip|.gz)$')


echo "/flywheel/v0"
ls -lR /flywheel/v0

