#!/bin/bash

BaseDir=/data/XNAT/archive
Depth=3
Filter="^"
Name='[0-9][0-9][0-9][0-9][0-9][0-9]_*'

cmd=$(basename "$0")

# /data/XNAT/archive/NACC-SC/arc001/118439_20190305_3T/SCANS/1/DICOM/*.dcm

function getDicomDirs {
	local BaseDir="$1"
	local Depth="$2"
	local Name="$3"
	local Filter="$4"

	if [ -d "$BaseDir" ]
	then
		find "$BaseDir" -mindepth "$Depth" -maxdepth "$Depth" -name "$Name" | grep -E "$Filter"
	fi
}


while getopts b:g:p:S: arg
do
	case "$arg" in
		b|g|p|S)
			eval "opt_${arg}=${OPTARG:=1}"
			;;
	esac
done

shift $(($OPTIND - 1))

if [ -n "$opt_p" ]
then
	Projects=( $(echo "$opt_p" | sed 's:,:\n:g' | sed 's:^:'"$BaseDir"'/:') )
else
	Projects=( $(find "$BaseDir" -mindepth 1 -maxdepth 1 -type d) )
fi

for Project in "${Projects[@]}"
do
    Sessions=()
    if [ -n "$1" ]
    then
	for Session in "$@"
	do
	    if [ -d "${Project}/arc001/${Session}" ]
	    then
		Sessions+=( "${Project}/arc001/${Session}" )
	    fi
	done
    else
	Sessions=( $(getDicomDirs "${Project}" 2 "$Name" "$Filter") )
    fi
	
    if [ "${#Sessions[@]}" -gt 0 ]
    then
	echo "${Sessions[@]}" | tr ' ' '\n'
    fi
done
