#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse
import fwgearutils

if __name__ == '__main__':

    import argparse

    CmdName = os.path.basename(sys.argv[0])

    ap = argparse.ArgumentParser()
    ap.add_argument('-z', '--zip-info',  action='store_true', help='include zip file information')
    ap.add_argument('-v', '--verbose',  action='store_true', help='print progress info')
    ap.add_argument('path', nargs=1, type=str, default=None, help='group/project')

    args = ap.parse_args()

    fw = fwgearutils.getFW(args)
    if (not fw):
        print("%s : unable to initialize flywheel object" % (CmdName), file=sys.stderr)
        sys.exit(1)

    c = fw.lookup(args.path[0])

    j = fwgearutils.sloppyCopy(c)

    if (type(c) == flywheel.models.resolver_project_node.ResolverProjectNode):
        Sessions = []
        for s in c.sessions():
            if (args.verbose):
                print("%s : '%s'" % (CmdName, s.label), file=sys.stderr)

            session = fw.get(s.id)
            Session = fwgearutils.sloppyCopy(session)
            Acquisitions = []
            for a in session.acquisitions():
                if (args.verbose):
                    print("%s : '%s/%s'" % (CmdName, s.label, a.label), file=sys.stderr)

                aprime = fw.get(a.id)

                Files = []
                if (args.zip_info):
                    for f in aprime.files:
                        if (args.verbose):
                            print("%s : '%s/%s/%s'" % (CmdName, s.label, a.label, f.name), file=sys.stderr)

                        File = fwgearutils.sloppyCopy(f)
                        if (re.search('\.zip$', f.name)):
                            if (f.size > 0):
                                try:
                                    File['zip_info'] = fwgearutils.sloppyCopy(aprime.get_file_zip_info(f.name))
                                    File['zip_member_count'] = len(File['zip_info']['members'])

                                    Files.append(File.copy())
                                except (flywheel.rest.ApiException) as e:
                                    print("%s : %s/%s(%s).get_file_zip_info failed on '%s' : %s - %s\n" % (CmdName, s.label, a.label, aprime.id, f.name, e.status, e.reason), file=sys.stderr)
                                    continue
                            else:
                                    print("%s : Size of '%s/%s(%s)/%s' is 0 : Skipping\n" % (CmdName, s.label, a.label, aprime.id, f.name), file=sys.stderr)
                                    continue

                acquisition = fwgearutils.sloppyCopy(aprime)
                acquisition['files'] = Files
                Acquisitions.append((acquisition))

            Session['acquisitions'] = Acquisitions.copy()


            Sessions.append(Session.copy())

        j['sessions'] = Sessions

    print(json.dumps(j))

