#!/bin/bash

cmd=$(basename "$0")

while getopts "agnpP:sv" arg
do
	case "$arg" in
	     a|g|n|p|P|s|v)
		eval "opt_${arg}=${OPTARG:=1}"
		;;
	esac
done

shift $((OPTIND - 1))

JQExpr=".context.project"
if [ -n "$opt_a" ]
then
	JQExpr=".context"

elif [ -n "$opt_g" ]
then
	JQExpr=".context.group"
elif [ -n "$opt_p" ]
then
	JQExpr=".context.project"
elif [ -n "$opt_s" ]
then
	JQExpr=".context.site"
elif [ -n "$opt_P" ]
then
	JQExpr="$opt_P"
fi

Project="$1"
Json=$(pullFWProjectInfo "$Project")
rc=$?
if [ "$rc" == 0 ]
then
    echo "$Json"| jq "$JQExpr"
    rc=$?
fi

exit "$rc"


