#!/bin/bash

# syncs NACC-SC AshsHarP reports to INDD

cmd=$(basename "$0")

GroupProject="dwolklab/NACC-SC"
Gear=ashsharpicv

INDDToc=$(mktemp /tmp/${cmd}-XXXXX)
ssh cx2go "smbclient //cndr-indd.uphs.pennhealth.prv/mrireport -m SMB2 -A ~/AshsHarpIcv_pipeline/auth.txt  -c dir 2> /dev/null" | awk '{print $1}' | grep -P '^\d{6}(\.\d{2})?_\d{8}.pdf$' | sort  > "$INDDToc"

FWReports=$(getFWProjectAnalyses -g "$Gear" "$GroupProject" | grep .pdf | grep _3T_)

FWINDDColumn=$(echo "$FWReports" | cut -f 2 -d ' ' | ashsharp2INDDReportName)

FWFullReportInfo=$(paste <(echo "$FWReports") <(echo "$FWINDDColumn") | sort -k +3)

# Sometimes there can be multiple analyses run on the same session so we want the sort -u to prevent unneeded downloads
ReportsToDownload=$(diff <(echo "$FWFullReportInfo" | awk '{print $3}' | sort -u) "$INDDToc" | grep '<' | cut -f 2 -d ' ')

if [ -n "$ReportsToDownload" ]
then
	tmpdir=$(mktemp -d /tmp/${cmd}-XXXXXX)
	cd "$tmpdir"

	AidFids=()
	for i in $ReportsToDownload
	do
		AidFid=$(echo "$FWFullReportInfo" | grep "$i$" | cut -f 1 -d ' ' | head -n 1)
		AidFids+=("$AidFid")
	done
	
	getFWProjectAnalyses -v -D -d "$tmpdir" "${AidFids[@]}"

	for i in *.pdf
	do
		InddName=$(echo "$i" | ashsharp2INDDReportName)
		cat "$i" | ssh cx2go "smbclient //cndr-indd.uphs.pennhealth.prv/mrireport -m SMB2 -A ~/AshsHarpIcv_pipeline/auth.txt  -c 'put - $InddName' 2> /dev/null "
	done

	rm -rf "$tmpdir"
fi

# rm "$INDDToc"