#!/bin/bash

cmd=$(basename "$0")

function yyyymmdd2us {
	 local Date="$1"
	 
	 echo $Date | sed -E 's,([0-9]{4})([0-9]{2})([0-9]{2}),\2/\3/\1,'
}

function us2yyyyddmm {
	 local Date="$1"
	 
	 echo $Date | sed -E 's,([0-9]{2})/([0-9]{2})/([0-9]{4}),\3\1\2,'
}

Project="$1"

ScanDatesJson=$(pullFWProjectContext "$Project" | jq .Scandates_CINRA)

jq -r ".sessions[] | (\"\(._id) \(.timestamp) \(.subject.label) \(.label)\")" /tmp/loughead_lab/NBR_824061.json | while read SessionID MachineScanDate StartTime SubjectLabel SessionLabel
do
	UsScanDate=$(yyyymmdd2us $MachineScanDate)
	
	read Asid Stid <<< $(echo "$ScanDatesJson" | jq -r ".[]|select(.ScanDate == \"$UsScanDate\") | \"\(.ASID) \(.STID)\"")
	if [ -z "$Stid" ]
	then
		Stid=MissingData
	fi

	PaddedAsid=$(printf "%06d" $Asid)

	echo "mv '$SessionID' '$MachineScanDate' '$StartTime' '$SubjectLabel' '$SessionLabel' => '$PaddedAsid' '$Stid'"
done

