#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse
import fwgearutils

if __name__ == '__main__':

    import argparse

    CmdName = os.path.basename(sys.argv[0])

    ap = argparse.ArgumentParser()
    ap.add_argument('path', nargs=1, type=str, default=None, help='group/project')

    args = ap.parse_args()

    ApiKey = fwgearutils.getApiKey(args)

    try:
        fw = flywheel.Client()
    except (OSError, Exception) as e:
        try:
            fw = flywheel.Client(ApiKey,root=True)
        
        except (OSError, Exception) as e2:
            print("e2",e2, file=sys.stderr)
            print("e",e, file=sys.stderr)
            sys.exit(1)


    c = fw.lookup(args.path[0])

    j = fwgearutils.sloppyCopy(c)

    Sessions = []
    for s in c.sessions():
        session = fw.get(s.id)
        Session = fwgearutils.sloppyCopy(session)
        Acquisitions = []
        for a in session.acquisitions():
            acquisition = fw.get(a.id)

            Acquisitions.append(fwgearutils.sloppyCopy(acquisition))
            
        Session['acquisitions'] = Acquisitions.copy()


        Sessions.append(Session.copy())

    j['sessions'] = Sessions

    print(json.dumps(j))

