#!/bin/bash

DefaultFlywheelDir=/flywheel/v0
DefaultConfigFile=${DefaultFlywheelDir}/config.json

export PATH=/flywheel/v0:$PATH

ApiKey=$(getFlywheelApiKey)

ProjectGearID=$(jq -r '.["config"]["ProjectName"]' "$DefaultConfigFile")
if [ -z "$ProjectGearID" -o "$ProjectGearID" == 'null' -o "$ProjectGearID" == 'default' ]
then
    ProjectGearID=$(jq -r '.["destination"]["id"]' "$DefaultConfigFile")
fi

Json=$(pullFlywheelProjectContext "$ProjectGearID")
if [ -n "$Json" ]
then
    echo "ProjectContextJson: $Json"
    for k in site group project
    do
	echo "$Json" | jq '.["'$k'"]["filesystem"]' | json2dir -v -C / 
    done
fi
