#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse
import fwgearutils
import pyjq

from os.path import expanduser

def updateNestedDict(d, keypath, ud):
    if (len(d.keys()) == 0):
        d.update(ud)
    elif (len(keypath) == 1):
        try:
            d[keypath[0]].update(ud)
        except KeyError:
            return(None)
    else:
        try:
            updateNestedDict(d[keypath[0]],keypath[1:],ud)
        except KeyError:
            return(None)


if __name__ == '__main__':
    import argparse
    import tempfile

    CmdName = os.path.basename(sys.argv[0])

    ap = argparse.ArgumentParser()

    ap.add_argument('-d', '--debug', action='store_true', dest='debug', help='print additional debugging info')
    ap.add_argument('-n', '--noop', action='store_true', help='do not update the context')
    ap.add_argument('-P', '--path',action='store', nargs=1, default=['.context.project'], help='jq path specification for project info.  default is .context.project. Use "-P ." to get the entire info')
    ap.add_argument('project', nargs=1, help='group/project')
    args = ap.parse_args()

    #print("project = '%s'" % (args.project))

    ApiKey = fwgearutils.getApiKey(args)

    try:
        fw = flywheel.Client()
    except (OSError, Exception) as e:
        try:
            fw = flywheel.Client(ApiKey,root=True)
        
        except (OSError, Exception) as e2:
            print("e2",e2)
            print("e",e)
            sys.exit(1)
 
    except (IOError) as e:
        print("pushFlywheelProjectContext", e.args, file=sys.stderr)
        sys.exit(1)


    if (args.project):
        try:
            container = fw.get(args.project[0])
            if ('gear_info' in container.keys()):
                ProjectID = container.parents.project
                project = fw.get(ProjectID)

        except flywheel.rest.ApiException as e:
            try:
                project = fw.lookup(args.project[0])

            except flywheel.rest.ApiException as e:
                print("%s : Cannot find project by '%s' : %s" % (CmdName, args.project[0], e.reason), file=sys.stderr)
                sys.exit(e.status)

    ProjectInfoDict = fwgearutils.decodeKeys(project.info)

    print(json.dumps(pyjq.all(args.path[0], ProjectInfoDict)[0]))
