#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse
import fwgearutils
import pyjq

from os.path import expanduser

def updateNestedDict(d, keypath, ud):
    if (len(d.keys()) == 0):
        d.update(ud)
    elif (len(keypath) == 1):
        try:
            d[keypath[0]].update(ud)
        except KeyError:
            return(None)
    else:
        try:
            updateNestedDict(d[keypath[0]],keypath[1:],ud)
        except KeyError:
            return(None)


if __name__ == '__main__':
    import argparse
    import tempfile

    CmdName = os.path.basename(sys.argv[0])

    ap = argparse.ArgumentParser()

    ap.add_argument('-d', '--debug', action='store_true', dest='debug', help='print additional debugging info')
    ap.add_argument('-n', '--noop', action='store_true', help='do not actually update the info')
    ap.add_argument('-v', '--verbose', action='store_true', help='show what is being done')
    ap.add_argument('project', nargs=1, help='group/project')
    ap.add_argument('jsonfile', nargs='?', help='path to json file to upload to context, defaults to stdin')
    args = ap.parse_args()

    #print("project = '%s'" % (args.project))
    #print("jsonfile = '%s'" % (args.jsonfile))

    ApiKey = fwgearutils.getApiKey(args)

    try:
        fw = flywheel.Client()
    except (OSError, Exception) as e:
        try:
            fw = flywheel.Client(ApiKey,root=True)
        
        except (OSError, Exception) as e2:
            print("e2",e2)
            print("e",e)
            sys.exit(1)
 
    except (IOError) as e:
        print("pushFlywheelProjectContext", e.args, file=sys.stderr)
        sys.exit(1)


    if (args.project):
        try:
            container = fw.get(args.project[0])
            if ('gear_info' in container.keys()):
                ProjectID = container.parents.project
                project = fw.get(ProjectID)

        except flywheel.rest.ApiException as e:
            try:
                project = fw.lookup(args.project[0])

            except flywheel.rest.ApiException as e:
                print("%s : Cannot find project by '%s' : %s" % (CmdName, args.project[0], e.reason), file=sys.stderr)
                sys.exit(e.status)

    try:
        with open(args.jsonfile, 'r') if args.jsonfile else sys.stdin as jsonfile:
            Json = json.load(jsonfile)

    except IOError as e:
        print("%s : Cannot open '%s' : %s" % (CmdName, args.jsonfile, e.args[1]), file=sys.stderr)
        exit(e.args[0])
        
    if (args.debug):
        print("Json", json.dumps(Json))

    if (not args.noop):
        project.update_info(fwgearutils.encodeKeys(Json))

