#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse
import fwgearutils


if __name__ == '__main__':

    import argparse

    CmdName = os.path.basename(sys.argv[0])

    ap = argparse.ArgumentParser()
    # Projects, Subjects, Sessions, Acquisitions and Analyses are containers
    # but Analyses are only containers within the other containers and not from the flywheel object
    cap = ap.add_mutually_exclusive_group()
    cap.add_argument('-a', '--acquisitions',  action='store_true', help='find acquisition information')
#    cap.add_argument('-A', '--analyses',  action='store_true', help='find analyses information')
    cap.add_argument('-p', '--projects',  action='store_true', help='find project information')
    cap.add_argument('-s', '--subjects',  action='store_true', help='find subject information')
    cap.add_argument('-S', '--sessions',  action='store_true', help='find session information')

    ap.add_argument('findargs', nargs='+', type=str, default=None, help='find args')

    args = ap.parse_args()

    fw = fwgearutils.getFW(args)
    if (not fw):
        print("%s : unable to initialize flywheel object" % (CmdName), file=sys.stderr)
        sys.exit(1)

    res = None

    if (args.acquisitions):
        res = fw.acquisitions.find(*args.findargs)
#    if (args.analyses):
#        print(fw.__dir__())
#        res = fw.analyses.find(*args.findargs)
    if (args.projects):
        res = fw.projects.find(*args.findargs)
    if (args.subjects):
        res = fw.subjects.find(*args.findargs)
    if (args.sessions):
        res = fw.sessions.iter_find(*args.findargs)

    #
    # Want to add analyses, get, zip-info from fw2json
    #
    output = []
    for r in res:
        output.append(r)

    print(json.dumps(fwgearutils.sloppyCopy(output)))

