#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse
import fwgearutils


if __name__ == '__main__':

    import argparse

    CmdName = os.path.basename(sys.argv[0])

    ap = argparse.ArgumentParser()
    ap.add_argument('-n', '--no-op', action='store_true', help='No-op')
    ap.add_argument('-v', '--verbose', action='store_true', help='Verbose')
    ap.add_argument('id', nargs="+", type=str, default=None, help='group/project|ProjectID')

    args = ap.parse_args()

    fw = fwgearutils.getFW(args)
    if (not fw):
        print("%s : unable to initialize flywheel object" % (CmdName), file=sys.stderr)
        sys.exit(1)

    for path in args.id:
        try:
            Container = fw.get(path)
        except (OSError, Exception) as e:
            try:
                Container = fw.lookup(path)
            except (OSError, Exception) as e:
                print("%s : fw.get and fw.lookup failed for '%s' : e = %s" %(CmdName, path, e), file=sys.stderr)
                sys.exit(1)

        if (args.verbose):
            print("%s : removing '%s'" % (CmdName, Container.label), file=sys.stderr)
            
        if (not args.no_op):
            try:
                fw.delete_container(Container._id)
            except (OSError, Exception) as e:
                print("%s : deleting '%s'(%s) failed %s" % (CmdName, Container.label, Container._id, e), file=sys.stderr)
