#!/bin/bash

cmd=$(basename "$0")

syntax="${cmd} [-c configfile] ConfigParam FW DicomParam [default]"

ConfigFile=/flywheel/v0/config.json

while getopts c: args
do
	case "$args" in
	     c)
		eval "opt_${args}=${OPTARG:=1}"
		;;
	esac	
done

shift $(($OPTIND - 1))

if [ -n "$opt_c" ]
then
	ConfigFile="$opt_c"
fi

if [ ! -e "$ConfigFile" ]
then
	echo "$cmd : no such file '$ConfigFile'" 1>&2
	exit 1
fi

JQExpr=$(echo "$1" | sed -r 's/ / | /g; s/(\w+)/..|select(.\1)?|.\1/g')
ConfigParam=$(jq -r "$JQExpr" "$ConfigFile")
if [ -n "$ConfigParam" -a "$ConfigParam" != 'null' -a "$ConfigParam" != '' ]
then
	echo "$ConfigParam"
	exit 0
fi

IDExpr=$(echo "$2" | cut -f 1 -d ,)
LabelExpr=$(echo "$2" | cut -f 2 -d ,)

FWDestinationID=$(jq -r .destination.id "$ConfigFile")
FWID=$(fwget "$FWDestinationID" | jq -r "$IDExpr")
if [ "$FWID" != 'null' ]
then
    DicomParam=$(fwget "$FWID" | jq -r "$LabelExpr")
    if [ "$DicomParam" != null ]
    then
	echo "$DicomParam"
	exit 0
    fi
fi

DicomParam=$(jq -r '.["inputs"]["dicom"]["object"]["info"]["'$3'"]' "$ConfigFile")
#if [ -n "$DicomParam" -a "$DicomParam" != 'null' -a "$ConfigParam" != '' ]
if [ -n "$DicomParam" -a "$DicomParam" != 'null' ]
then
	echo "$DicomParam"
	exit 0
fi

if [ -n "$4" ]
then
	echo "$4"
	exit 0
fi

exit 1
