#!/bin/bash

DefaultFlywheelDir=/flywheel/v0
DefaultConfigFile=${DefaultFlywheelDir}/config.json
opt_d=/

export PATH=/flywheel/v0:$PATH

while getopts c:d: args
do
    case $args in
	c|d)
	    eval "opt_${args}=${OPTARG:=1}"
	    ;;
    esac
done

shift $(($OPTIND - 1))

if [ -n "$opt_c" ]
then
    DefaultConfigFile="$opt_c"
fi

ApiKey=$(getFlywheelApiKey)

ProjectGearID=$(jq -r '.["destination"]["id"]' "$DefaultConfigFile")
Json=$(pullFWProjectContext -a "$ProjectGearID")
if [ "$?" != 0 ]
then
    ProjectGearID=$(getGearParam -c "$DefaultConfigFile" ProjectName ImageComments UnknownProjectName)
    Json=$(pullFWProjectContext -a "$ProjectGearID")
fi

if [ -n "$Json" ]
then
    for k in site group project
    do
	echo "$Json" | jq '.["'$k'"]["filesystem"]' | json2dir -v -C "$opt_d"
    done
fi
