#!/bin/bash

# syncs NACC-SC AshsHarP reports to INDD

# Assumptions
# + Only 3T reports are looked for
# + Each session only has a since analysis.  It is possible to run multiple analyses, but there is only room in the INDD for one of them.
# 

cmd=$(basename "$0")

syntax="$cmd [-f inddreporttofilter][-g gear][-n][-v] Group/Project"

function sys {
	  [ -n "${opt_n}${opt_v}" ] && echo "$cmd : $@" 1>&2
	  [ -n "$opt_n" ] || "$@"
}

opt_f='xxxxx'

while getopts f:g:nv arg
do
	case "$arg" in
	     f|g|n|v)
		eval "opt_${arg}=${OPTARG:=1}"
		;;
	esac
done

shift $(($OPTIND - 1))

if [ -n "$opt_g" ]
then
   Gear="$opt_g"
else
   Gear=ashsharpicv
fi

if [ -n "$1" ]
then
	GroupProject="$1"
else
	GroupProject="dwolklab/NACC-SC"
fi

INDDToc=$(mktemp /tmp/${cmd}-XXXXX)
ssh -x cx2go "smbclient //cndr-indd.uphs.pennhealth.prv/mrireport -m SMB2 -A ~/AshsHarpIcv_pipeline/auth.txt  -c dir 2> /dev/null" | awk '{print $1}' | grep -P '^\d{6}(\.\d{2})?_\d{8}.pdf$' | sort  | grep -v "$opt_f" > "$INDDToc"

[ -n "${opt_n}${opt_v}" ] && echo "$cmd : Got list of INDD reports" 1>&2

FWReports=$(getFWProjectAnalyses -g "$Gear" "$GroupProject" | grep '.pdf$')

[ -n "${opt_n}${opt_v}" ] && echo "$cmd : Got list of Flywheel reports from $GroupProject" 1>&2

FWINDDColumn=$(echo "$FWReports" | cut -f 2 -d ' ' | ashsharp2INDDReportName)

FWFullReportInfo=$(paste <(echo "$FWReports") <(echo "$FWINDDColumn") | sort -k +3)

# Sometimes there can be multiple analyses run on the same session so we want the sort -u to prevent unneeded downloads
ReportsToDownload=$(diff <(echo "$FWFullReportInfo" | awk '{print $3}' | sort -u) "$INDDToc" | grep '<' | cut -f 2 -d ' ')

if [ -n "$ReportsToDownload" ]
then
	[ -n "${opt_n}${opt_v}" ] && echo "$cmd : ReportsToDownload = " $ReportsToDownload 1>&2

	tmpdir=$(mktemp -d /tmp/${cmd}-XXXXXX)
	cd "$tmpdir"

	AidFids=()
	for i in $ReportsToDownload
	do
		AidFid=$(echo "$FWFullReportInfo" | grep "$i$" | cut -f 1 -d ' ' | head -n 1)
		AidFids+=("$AidFid")
	done
	
	DownloadedFiles=$(sys getFWProjectAnalyses -D -d "$tmpdir" "${AidFids[@]}" | awk '{print $2}')

	for i in $DownloadedFiles
	do
		InddName=$(echo "$i" | ashsharp2INDDReportName)
		cat "$i" | ssh -x cx2go "smbclient //cndr-indd.uphs.pennhealth.prv/mrireport -m SMB2 -A ~/AshsHarpIcv_pipeline/auth.txt  -c 'put - $InddName' 2> /dev/null "
		[ -n "${opt_n}${opt_v}" ] && echo "$cmd : copy Flywheel/$GroupProject '$i' to INDD:'//cndr-indd.uphs.pennhealth.prv/mrireport/$InddName'" 1>&2
	done

	rm -rf "$tmpdir"
else
	[ -n "${opt_n}${opt_v}" ] && echo "$cmd : No Flywheel reports to sync to INDD" 1>&2
fi

# rm "$INDDToc"
