#!/bin/bash


#
# BiqQuery Tables
#   projectid.dataset.table
# eg
#   pennbrain-center.BillingAllocation.FlywheelCosts
# project: pennbrain-center
# dataset: BillingAllocation
# table:   FlywheelCosts
#

function sys {
    [ -n "${opt_n}${opt_v}" ] && echo "$@" 1>&2
    [ -n "${opt_n}" ] || "$@"
}

CmdName=$(basename "$0")
syntax="${CmdName} [-D WorkDir][-d Dataset][-f][-j JobReport][-m MM][-n][-p Project][-t Table][-u UsageReport][-v][-y YYYY]"

while getopts D:d:fj:m:np:t:u:vy: arg
do
	case $arg in
	     D|d|f|j|m|n|p|t|u|v|y)
		eval "opt_${arg}=${OPTARG:=1}"
		;;
	esac
done

shift $((OPTIND - 1))

WorkDir=.
[ -n "$opt_D" ] && WorkDir="$opt_D"

nowmonth=$(date +%Y-%m-15)
Year=$(date --date="$nowmonth -1 month" +'%Y')
[ -n "$opt_y" ] && Year="$opt_y"

Month=$(date --date="$nowmonth -1 month" +'%m')
[ -n "$opt_m" ] && Month="$opt_m"

Dataset=BillingAllocation
[ -n "$opt_d" ] && Dataset="$opt_d"

Project=pennbrain-center
[ -n "$opt_p" ] && Project="$opt_p"

#
# Make sure the Dataset exists
#

if ! (bq show "${Project}:${Dataset}" > /dev/null )
then
	if [ -n "$opt_f" ]
	then
		sys bq mk "${Project}:${Dataset}"
	else
		echo "${CmdName} : '${Project}:${Dataset}' does not exist.  Use -f to create" 1>&2
		exit 1
	fi
fi

Args=()
Args+=( -p "${Project}" )
Args+=( -d "${Dataset}" )
Args+=( -m "${Month}" )
Args+=( -y "${Year}" )

[ -n "$opt_v" ] && Args+=( -v )


sys createCostsTable -o GcpNonFlywheelCosts -w 'project.name != "upenn-flywheel"' -m "${Month}" -y "${Year}"
sys createCostsTable -o FlywheelCosts -w 'project.name = "upenn-flywheel"' -m "${Month}" -y "${Year}"

KeepFile=-k

FwJobReportFile="${WorkDir}/${Year}-${Month}-FwJobReport.csv"
if [ -n "$opt_j" ]
then
    FwJobReportFile="$opt_j"
fi
    
sys uploadJobsReport $KeepFile "${Args[@]}" "$FwJobReportFile"

FwUsageReportFile="${WorkDir}/${Year}-${Month}-FwUsageReport.csv"
if [ -n "$opt_u" ]
then
    FwUsageReportFile="$opt_u"
fi
    
sys uploadUsageReport $KeepFile "${Args[@]}" "$FwUsageReportFile"

FwSessionReportFile="${WorkDir}/${Year}-${Month}-FwSessionReport.csv"
sys uploadSessionReport $KeepFile "${Args[@]}" "$FwSessionReportFile"

sys createTempTables "${Args[@]}" 

sys allocateProjectCosts "${Args[@]}" 
sys allocateProjectGearCosts "${Args[@]}" 

sys downloadILabCharges -f "${Args[@]}" > "${Year}-${Month}-iLabFlywheelCharges.csv"
sys downloadILabCharges -g "${Args[@]}" > "${Year}-${Month}-iLabNonFwGcpILabCharges.csv"
sys downloadILabCharges -M "${Args[@]}" > "${Year}-${Month}-iLabFlywheelMriCharges.csv"
  
