#!/bin/bash

cmd=$(basename $0)

FromGroupProject=unknown/Unsorted
ToProject=Unsorted
LookUpTable=~/Work/CfN/flywheel/AdminScripts/StudyDescriptionToGroup

while getopts nl:v arg
do
	case "$arg" in
	     n|l|v)
		eval "opt_${arg}='${OPTARG:=1}'"
		;;
	esac
done

shift $((OPTIND - 1))

StudyDescriptions=()

if [ -n "$1" ]
then
	if [ -e "$1" ]
	then
	   StudyComments=($(< "$1"))
	else
	   StudyComments=("$@")
	fi
else
        while read line
	do 
	    StudyComments+=("$line")
	done < <(cut -f 3 -d : /tmp/unknownUnsorted.csv | sort -u)
	#echo "StudyComments: ${StudyComments[0]}"
fi


function sys {
	 [ -n "${opt_n}${opt_v}" ] && echo "$@" 1>&2
	 [ -n "$opt_n" ] || "$@"
}

function getDestGroup {
	 local StudyComments="$(echo $1 | sed 's/\^/\\^/; s/Copy of //')"
	 local res
	 local n

	 res=$(grep -P "^${StudyComments}\s" "${LookUpTable}" | sed -r 's/^.*\s//')
	 
	 if [ -n "$res" ]
	 then
		echo "$res"
		return 0
	fi

	return 1
}

function getSubjectSession {
	 local StudyComments="$(echo $1 | sed 's/\^/\\^/; s/Copy of //')"
	 local res
	 local n

	 res=$(grep -P ":${StudyComments}:" /tmp/unknownUnsorted.csv | cut -f 1 -d :)
	 
	 if [ -n "$res" ]
	 then
		echo "$res"
		return 0
	fi

	return 1
}

for i in "${StudyComments[@]}"
do
	StudyComments="$i"
	ToGroup=$(getDestGroup "$StudyComments")

	if [ -n "$ToGroup" ]
	then
		while read ss
		do
		    sys fwmv "fw://${FromGroupProject}/${ss}" "${ToGroup}/${ToProject}/${ss}"
		done < <(getSubjectSession "$StudyComments")
	else		
		echo No entry for "'$StudyComments'" in "'$LookUpTable'" 1>&2
	fi
done
