#!/bin/bash

cmd=$(basename $0)

FromGroupProject=unknown/Unsorted
ToProject=Unsorted
LookUpTable=~/Work/CfN/flywheel/AdminScripts/StudyDescriptionToGroup

while getopts c:fl:nv arg
do
	case "$arg" in
	     c|f|l|n|v)
		eval "opt_${arg}='${OPTARG:=1}'"
		;;
	esac
done

shift $((OPTIND - 1))

if [ -n "$opt_f" ]
then
    CmdArgs+=("-f")
fi

if [ -n "$opt_l" ]
then
    LookUpTable="$opt_l"
fi

StudyDescriptions=()

if [ -n "$opt_c" ]
then
    CSVFile="$opt_c"
fi

if [ -n "$1" ]
then
	if [ -e "$1" ]
	then
	   StudyComments=($(< "$1"))
	else
	   StudyComments=("$@")
	fi
else
        while read line
	do 
	    StudyComments+=("$line")
	done < <(cut -f 3,4 -d , /tmp/unknownUnsorted.csv | sed 's/"//g; s/,/\n/g' | sort -u)
	#echo "StudyComments: ${StudyComments[0]}"
fi


function sys {
	 [ -n "${opt_n}${opt_v}" ] && echo "$@" 1>&2
	 [ -n "$opt_n" ] || "$@"
}

function getDestGroup {
	 local StudyComments="$(echo $1 | sed 's/\^/\\^/; s/\"//g; s/Copy of //')"
	 local res
	 local n

	 res=$(grep -P "^${StudyComments}\s" "${LookUpTable}" | sed -r 's/^.*\s//' | sed 's/"//g' )
	 
	 if [ -n "$res" ]
	 then
		echo "$res"
		return 0
	fi

	return 1
}

function getSubjectSession {
	 local StudyDescription="$(echo $1 | sed 's/\^/\\^/')"
	 local res
	 local n

	 res=$(grep -P ",\"(Copy of )?${StudyDescription}\"," /tmp/unknownUnsorted.csv | sed 's/"//g' | cut -f 1 -d , )
	 
	 if [ -n "$res" ]
	 then
		echo "$res"
		return 0
	fi

	return 1
}

for i in "${StudyComments[@]}"
do
	StudyComments="$i"
	ToGroup=$(getDestGroup "$StudyComments")

	if [ -n "$ToGroup" ]
	then
		while read FromPath
		do
		    ToPath=$(echo "$FromPath" | sed 's,^[^/]*/,,')
		    sys fwmv "${CmdArgs[@]}" "fw://${FromPath}" "${ToGroup}/${ToPath}"
		done < <(getSubjectSession "$StudyComments")
	else		
		echo No entry for "'$StudyComments'" in "'$LookUpTable'" 1>&2
	fi
done
