#!/usr/bin/env python3

import sys
import re
import os
import flywheel
import json
import argparse

import fwgearutils

if __name__ == '__main__':

    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--config-json', type=str, default='/flywheel/v0/config.json', dest="config_json", help='Full path to the input config.json file.')
    ap.add_argument('--apikeyfile', type=str, default='~/.config/flywheel/api.key', dest="apikeyfile", help='Full path to the file containing the apikey.')
    ap.add_argument('--apikey', type=str, default=None, dest="apikey", help='apikey.')
    args = ap.parse_args()

    ApiKey = fwgearutils.getApiKey(args)

    print(ApiKey)
