#!/bin/bash -x

# updated 16:04

export FLYWHEEL=${FLYWHEEL:=/flywheel/v0}
export PATH=${FLYWHEEL}:$PATH

export FLYWHEEL_INPUTDIR="${FLYWHEEL}/input"
export FLYWHEEL_OUTPUTDIR="${FLYWHEEL}/output"

CONFIG_FILE=${FLYWHEEL}/config.json
GearName=ashs

echo 35.184.111.29 dss.itksnap.org >> /etc/hosts

echo "/flywheel/v0"
ls -lR /flywheel/v0

cat "$CONFIG_FILE"

bash -x installFWSupportFiles

if [ -e "/root/.alfabis/server" -a -e "/root/.alfabis/cookie_"*".jar" ]
then
	echo "Found itksnap cookie jar"
else
	echo "No itksnap cookie found.  Bailing"
	exit 1
fi

DSSService=$(getGearParam "${CONFIG_FILE}:.config.ASHS_Atlas" default:UnknownServiceName)
T1Path=$(getGearParam "${CONFIG_FILE}:.inputs.T1w.location.path")
T2Path=$(getGearParam "${CONFIG_FILE}:.inputs.T2w.location.path")

#itksnap-wt -dss-tickets-list


run_pipeline.sh -s "$DSSService" -d "$FLYWHEEL_OUTPUTDIR" -T "$T1Path" -t "$T2Path"


echo "/flywheel/v0"
ls -lR /flywheel/v0

